### ISSUE TITLE
Unable to fill a pdf

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/pdfparser#9]
@rogerawad I'm not sure if I'm running the command correctly, but I think I am, and I am unable to fill a test pdf.

Here is an example command that fails for me:

``` bash
java -jar pdfparser.jar set_fields data/sample_pdfs/CleanSlateSinglePage.pdf data/sample_output/test.pdf '{"Dates arrested outside SF": "", "Arrested outside SF": "No", "How did you hear about the Clean Slate Program": "From a wonderful friend", "US Citizen": "Yes", "Address City": "Little Town", "May we leave voicemail": "Yes", "Serving a sentence": "No", "May we send mail here": "Yes", "Last Name": "Manatee", "On probation or parole": "No", "Other phone number": "", "Address State": "CA", "First Name": "Berry", "Date": "09/09/2016", "MI": "H", "Address Street": "111 Main Street", "Home phone number": "", "Charged with a crime": "No", "Date of Birth": "09/09/9999", "Social Security Number": "999-99-9999", "Monthly expenses": "1000", "Email Address": "berry.happy.manatee@gmail.com", "If probation where and when?": "", "Cell phone number": "999-999-9999", "Work phone number": "", "Employed": "No", "Address Zip": "01092", "What is your monthly income": "0", "Drivers License": "D9999999"}'
```

I have tried many variations on how to handle the JSON input, but I cannot get past the same error.

The error I get is:

``` bash
Usage: pdfparser get_fields filename or pdfparser set_fields srcFileName destFileName json
```

Looking at `testWriteText`, I wonder how the last two args are handled.

``` java
    private static String[] testWriteText() {
        String[] args = new String[3];
        args[0] = "set_fields";
        args[1] = "testpdfs/text.pdf";
        args[2] = new JsonWithData().getFileString("text.pdf");
        return args;
    }
```

This looks like it will set `args[2]` as a JSON, and I'm not sure where `destFileName` is positioned in the args. I've tried several variations on the order of args. None seem to work..

**Comment by rogerawad** [comment]
The writer expects the json to be in the same format that the reader sent:  
{ fields: [  { "key1" : "value1" }, { "key2" : "value2" }  ] }
your json is missing the fields: [] array

**Comment by bengolder** [comment]
Ohhh! Okay, thanks!

**Comment by bengolder** [comment]
I tried that JSON structure and I’m getting the same error.

**Comment by rogerawad** [comment]
sorry, I should've caught this earlier.  you're missing an argument most likely the destination file assuming that text.pdf is the source file.  The command args should be:
"set_fields" "srcFileName" "destFileName" "json"

**Comment by rogerawad** [comment]
I also have a bug that I'm fixing right now.

**Comment by bengolder** [comment]
I double-checked the args. It looks correct to me. Here's my most recent attempt (it still returns the same error)

``` bash
java -jar pdfparser.jar \
        set_fields \
        data/sample_pdfs/CleanSlateSinglePage.pdf \
        data/sample_output/test.pdf \
        '{"fields": [{"Arrested outside SF": "No"}, {"How did you hear about the Clean Slate Program": "From a wonderful friend"}, {"US Citizen": "Yes"}, {"Address Zip": "01092"}, {"May we send mail here": "Yes"}, {"Other phone number": ""}, {"If probation where and when?": ""}, {"Address Street": "111 Main Street"}, {"Dates arrested outside SF": ""}, {"Monthly expenses": "1000"}, {"Cell phone number": "999-999-9999"}, {"Address State": "CA"}, {"Work phone number": ""}, {"Employed": "No"}, {"May we leave voicemail": "Yes"}, {"Serving a sentence": "No"}, {"Last Name": "Manatee"}, {"MI": "H"}, {"Charged with a crime": "No"}, {"First Name": "Berry"}, {"On probation or parole": "No"}, {"Social Security Number": "999-99-9999"}, {"Email Address": "berry.happy.manatee@gmail.com"}, {"What is your monthly income": "0"}, {"Date": "09/09/2016"}, {"Drivers License": "D9999999"}, {"Home phone number": ""}, {"Date of Birth": "09/09/9999"}, {"Address City": "Little Town"}]}'
```

returns

``` bash
Usage: pdfparser get_fields filename or pdfparser set_fields srcFileName destFileName json
```

**Comment by rogerawad** [comment]
I'm uploading a new jar on slack that fixes a bug with the args.

**Comment by bengolder** [comment]
Thanks. Tried the new `.jar`, but I'm still getting the same error with the last command I posted.

**Comment by rogerawad** [comment]
this looks like the old jar.  I changed the return error to be more specific so if you're using set_fields, it will return:  
pdfparser set_fields srcFileName destFileName json

**Comment by bengolder** [comment]
You're right! I tried erasing the `.jar`s that I had and re-downloaded the one from Slack. It's still not working, but it's giving me a different error (still testing with the [last command I posted](https://github.com/rogerawad/pdfparser/issues/9#issuecomment-213255357)):

``` bash
Stream Closed
java.io.IOException: Stream Closed
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:326)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
    at com.itextpdf.text.pdf.OutputStreamCounter.write(OutputStreamCounter.java:105)
    at com.itextpdf.text.pdf.PdfObject.toPdf(PdfObject.java:176)
    at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:149)
    at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:154)
    at com.itextpdf.text.pdf.PdfDictionary.toPdf(PdfDictionary.java:154)
    at com.itextpdf.text.pdf.PdfIndirectObject.writeTo(PdfIndirectObject.java:158)
    at com.itextpdf.text.pdf.PdfWriter$PdfBody.write(PdfWriter.java:403)
    at com.itextpdf.text.pdf.PdfWriter$PdfBody.add(PdfWriter.java:381)
    at com.itextpdf.text.pdf.PdfWriter.addToBody(PdfWriter.java:870)
    at com.itextpdf.text.pdf.PdfStamperImp.close(PdfStamperImp.java:434)
    at com.itextpdf.text.pdf.PdfStamperImp.close(PdfStamperImp.java:409)
    at com.itextpdf.text.pdf.PdfStamper.close(PdfStamper.java:231)
    at loaders.LocalPdfWriter.unload(LocalPdfWriter.java:62)
    at pdfParsers.JsonToPdfWriter.writeFields(JsonToPdfWriter.java:35)
    at PdfParser.writeJsonToPdf(PdfParser.java:85)
    at PdfParser.main(PdfParser.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by rogerawad** [comment]
I know.  I have a fix for it that I'd like to check in, but I'm getting invalid refspec anytime I modify a file in eclipse.  It seems like git in eclipse is out of sync with repo on github.
